---
title: "1225"
output: html_document
editor_options: 
  chunk_output_type: inline
---

Data analysis of human stampedes data by Nugroho Budianggoro (@nugi1209) for his blog [NadiData.com](https://nadidata.com/) 16-12-2021 -- updated 02-02-2022

Dataset source: [Shivam Bansal on Kaggle](https://www.kaggle.com/shivamb/human-stampede)

```{r}
# Imports

library(tidyverse)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(wordcloud2)
```

```{r}
# Read the dataset

df <- read.csv('https://github.com/nugi1209/NadiData.com/raw/main/1225_dataset.csv')

```

```{r}
# Convert the date column to Date format

df <- mutate(df, Date = as.Date(Date, format="%Y-%m-%d"))
df$Year <- format(df$Date, format="%Y")
head(df, n = 2)
```
```{r fig.align="center", echo=FALSE, fig.width=10}
# Plot number of death to year

ggplot(data=df, aes(y=Year, x=Number.of.Deaths)) + geom_bar(stat='identity') + ggtitle("Number of Deaths per Year")

```


```{r}
# Create data frame of grouped number of deaths by country

df_sum_ctr <- df %>%
                group_by(Country) %>%
                    summarise(sum = sum(Number.of.Deaths))

df_sum_ctr <- df_sum_ctr %>%
                rename(
                    Number.of.Deaths = sum
                )

head(df_sum_ctr[order(-df_sum_ctr$Number.of.Deaths),])

```

```{r fig.align="center", echo=FALSE, fig.width=10}
# Plot number of deaths per country

ggplot(data=df_sum_ctr, aes(y=reorder(Country,Number.of.Deaths), x=Number.of.Deaths)) + geom_bar(stat='identity') + ggtitle("Number of Deaths per Country")

```


```{r}
# Create data frame of group number of deaths by year

df_sum_yr <- df %>%
                group_by(Year) %>%
                    summarise(sum = sum(Number.of.Deaths))
head(df_sum_yr[order(-df_sum_yr$sum),])

```

```{r}
# Create data frame of incidents involving more than 500 deaths

df_ov_300 <- df[df[,"Number.of.Deaths"]>300, ]

# Plot the data

ggplot(data=df_ov_300, aes(y=reorder(Event.Name,Number.of.Deaths), x=Number.of.Deaths)) + geom_bar(stat='identity') + ggtitle("Highest Number of Deaths per Event")
       
```

```{r}

# Clean string from the place column so that we can conveniently process and compare it

# Make a function to clean string

clean_string <- function(string){
    res <- tolower(string)
    res <- stringr::str_replace_all(res, "[^a-zA-Z\\s]", " ")
    res <- stringr::str_replace_all(res, "[\\s]+", " ")
    str <- stringr::str_split(res, " ")[[1]]
    indexes <- which(res == "")
    if(length(indexes) > 0){
        res <- res[-indexes]
    }
    return(res)
}

# Clean string of place column

places <- clean_string(df$Place)

# Get duplicate values of cleaned places and count the rows

duplicated_places <- places[duplicated(places)]

duplicated_places <- unique(duplicated_places)

length(places[duplicated(places)])

```
```{r}
# Create copy of master data frame and add the cleaned places column to it

df1 <- df

df1$Place.Cleaned <- places

head(df1, n = 2)

```

```{r}

# Get all rows with duplicated cleaned places but remove the 'various' place

df_dup_places <- df1[df1$Place.Cleaned %in% duplicated_places, ]

df_dup_places <- df_dup_places[!(df_dup_places$Place.Cleaned=="various"),]

head(df_dup_places, n = 2)

```



```{r}
min(df$Year)

```

```{r}
# Get count of incidents per country

df_count_ctr <- df %>%
                group_by(Country) %>%
                    tally()

# Rename incident count column

df_count_ctr <- df_count_ctr %>%
    rename(
        Incident.Count = n
    )
head(df_count_ctr[order(-df_count_ctr$Incident.Count),])

```

```{r fig.align="center", echo=FALSE, fig.width=10}
# Plot incident count per country

ggplot(data=df_count_ctr, aes(y=reorder(Country,Incident.Count), x=Incident.Count)) + geom_bar(stat='identity') + ggtitle("Incident Count per Country")

```

```{r fig.align="center", echo=FALSE, fig.width=10}

# Group incident count by year

df_count_yr <- df %>%
                group_by(Year) %>%
                    tally()

df_count_yr <- df_count_yr %>%
                rename(
                    Incident.Count = n
                )
head(df_count_yr)

```


```{r fig.align="center", echo=FALSE, fig.width=10}

# Plot incident count by year

ggplot(data=df_count_yr, aes(y=Year, x=Incident.Count)) + geom_bar(stat='identity') + ggtitle("Incident Count per Year")
```

```{r}

df[df[,"Country"]=='Indonesia', ]

```

```{r}

# Create word cloud
text <- df$Description

docs <- Corpus(VectorSource(text))

docs <- docs %>%
            tm_map(removeNumbers) %>%
            tm_map(removePunctuation) %>%
            tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
# docs <- tm_map(docs, removeWords,c("people", "stampede"))

```

```{r}

dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing=TRUE)
df_words <- data.frame(word = names(words), freq=words)

```

```{r}

set.seed(13)
wordcloud(words=df_words$word, freq=df_words$freq, min.freq=1, max.words=100,
          random.order=FALSE, rot.per=0.35, colors = brewer.pal(8, "Dark2"))
```

```{r}

stopwords2 <- c('killed',
                'injured',
                'stampede',
                'least',
                'crowd',
                'died',
                'one',
                'police',
                'trying',
                'people',
                'many',
                'crushed',
                'death',
                'three',
                'women',
                'two',
                'occured',
                'others',
                'fell',
                'caused',
                'leading',
                'number',
                'trampled',
                'rushed',
                'causing',
                'day',
                'near',
                'deaths',
                'get',
                'tried',
                'new',
                'later',
                'end',
                'following',
                'injuries',
                'crush',
                'person',
                'tear',
                'panic',
                'india',
                'occurred')

docs2 <- tm_map(docs, removeWords,stopwords2)

dtm2 <- TermDocumentMatrix(docs2)
matrix2 <- as.matrix(dtm2)
words2 <- sort(rowSums(matrix2), decreasing=TRUE)
df_words2 <- data.frame(word = names(words2), freq=words2)

set.seed(123)
wordcloud(words=df_words2$word, freq=df_words2$freq, min.freq=1, max.words=30,
          random.order=FALSE, rot.per=0.35, colors = brewer.pal(8, "Dark2"))

```


