---
title: "Human Stampedes"
output:
  html_document:
    df_print: paged
---

Data analysis by Nugroho Budianggoro (@nugi1209) 16-12-2021

```{r}
library(tidyverse)
library(wordcloud)
library(RColorBrewer)
library(tm)
library(wordcloud2)
```


```{r}
df <- read.csv('https://raw.githubusercontent.com/nadidata/Blog/main/2021_12_16_human_stampedes_DATASET.csv')

```


```{r}
df <- mutate(df, Date = as.Date(Date, format="%Y-%m-%d"))
df$Year <- format(df$Date, format="%Y")
df
```
```{r fig.align="center", echo=FALSE, fig.width=10}
ggplot(data=df, aes(y=Year, x=Number.of.Deaths)) + geom_bar(stat='identity')

```
```{r}
df[order(-df$Number.of.Deaths),]
```
```{r}
```


```{r}
df_sum_ctr <- df %>%
                group_by(Country) %>%
                    summarise(sum = sum(Number.of.Deaths))
```


```{r}
head(df_sum_ctr[order(-df_sum_ctr$sum),])
head(df_sum_ctr)

```

```{r}
df_sum_yr <- df %>%
                group_by(Year) %>%
                    summarise(sum = sum(Number.of.Deaths))
head(df_sum_yr[order(-df_sum_yr$sum),])
head(df_sum_yr)

```

```{r}

df_ov_500 <- df[df[,"Number.of.Deaths"]>500, ]
ggplot(data=df_ov_500, aes(y=Country, x=Number.of.Deaths)) + geom_bar(stat='identity')
# head(df_ov_500)
```
```{r}
# unique(df[c("x1")])
unique(df[c("Place")])

```
```{r}
min(df$Year)
```
```{r fig.align="center", echo=FALSE, fig.width=10}
df_count_ctr <- df %>%
                group_by(Country) %>%
                    tally()
head(df_count_ctr[order(-df_count_ctr$n),])

ggplot(data=df_count_ctr, aes(y=reorder(Country,n), x=n)) + geom_bar(stat='identity')
```
```{r fig.align="center", echo=FALSE, fig.width=10}
df_count_yr <- df %>%
                group_by(Year) %>%
                    tally()
# head(df_count_yr[order(-df_count_yr$n),])

ggplot(data=df_count_yr, aes(y=reorder(Year,n), x=n)) + geom_bar(stat='identity')
```
```{r}
df[df[,"Country"]=='Indonesia', ]
```
```{r}
# CREATE WORD CLOUD
text <- df$Description

docs <- Corpus(VectorSource(text))

docs <- docs %>%
            tm_map(removeNumbers) %>%
            tm_map(removePunctuation) %>%
            tm_map(stripWhitespace)
docs <- tm_map(docs, content_transformer(tolower))
docs <- tm_map(docs, removeWords, stopwords("english"))
# docs <- tm_map(docs, removeWords,c("people", "stampede"))

```
```{r}
dtm <- TermDocumentMatrix(docs)
matrix <- as.matrix(dtm)
words <- sort(rowSums(matrix), decreasing=TRUE)
df_words <- data.frame(word = names(words), freq=words)

df_words
```

```{r}
set.seed(13)
wordcloud(words=df_words$word, freq=df_words$freq, min.freq=1, max.words=100,
          random.order=FALSE, rot.per=0.35, colors = brewer.pal(8, "Dark2"))
```

```{r}

stopwords2 <- c('killed',
                'injured',
                'stampede',
                'least',
                'crowd',
                'died',
                'one',
                'police',
                'trying',
                'people',
                'many',
                'crushed',
                'death',
                'three',
                'women',
                'two',
                'occured',
                'others',
                'fell',
                'caused',
                'leading',
                'number',
                'trampled',
                'rushed',
                'causing',
                'day',
                'near',
                'deaths',
                'get',
                'tried',
                'new',
                'later',
                'end',
                'following',
                'injuries',
                'crush',
                'person',
                'tear',
                'panic',
                'india',
                'occurred')

docs2 <- tm_map(docs, removeWords,stopwords2)

dtm2 <- TermDocumentMatrix(docs2)
matrix2 <- as.matrix(dtm2)
words2 <- sort(rowSums(matrix2), decreasing=TRUE)
df_words2 <- data.frame(word = names(words2), freq=words2)

set.seed(13)
wordcloud(words=df_words2$word, freq=df_words2$freq, min.freq=1, max.words=30,
          random.order=FALSE, rot.per=0.35, colors = brewer.pal(8, "Dark2"))

```


```{r}
sum(grepl("stadium", df$Description))

```

